### ISSUE TITLE
file error

### ISSUE THREAD

**Issue by XiaoXiao-MA** [imec-idlab/IEEE-802.11ah-ns-3#1]
i download the file, when extracted, the compressed file has been corrupted.

**Comment by ssi15004** [comment]
Hi, could I please ask you if you tried to download the code again?
I've just tried on my computer and it works fine for me.

**Comment by asljivo1** [comment]
Please follow the installation instructions, we updated them (instructions are more precise now):
-    Clone the project from git
-    Follow the instructions on https://www.nsnam.org/wiki/Installation to prepare all dependencies
-    Change into IEEE-802.11ah-ns-3 directory.
-    Configure waf: 
CXXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests
-    Build: 
./waf
-    Run the simulation: 
./waf --run test
