### ISSUE TITLE
How to disable RAW

### ISSUE THREAD

**Issue by vyktors23** [imec-idlab/IEEE-802.11ah-ns-3#14]
I am trying to study some scenarios with and without RAW, to compare performance, but the problem is that I did not understand how to disable RAW in the settings.

**Comment by asljivo1** [comment]
Hi,

First of all I apologise for the delayed answer. 

I am not certain if the RAW can be entirely disabled in the simulator (using only a setting-without changing the source code). If you want to see the performance without RAW, I would suggest a quick workaround:
a) define a single-slotted RAW to which all stations in the network are assigned, and set the duration of that RAW slot to your entire beacon interval, or
b) define a single-slotted RAW with RAW slot count parameter equal to 0 (if it is not permitted than 1, that would result in 500us or 620us slot duration respectively) and assign a dummy station to that RAW (a station that is never scheduled to transmit-on the higher layer). 

I never tried option b, I used option a in the past and that works for sure, for the option b I cannot guarantee as I haven't verified it.
