### ISSUE TITLE
Max number of slots per RAW

### ISSUE THREAD

**Issue by pedroliborio** [imec-idlab/IEEE-802.11ah-ns-3#15]
Hi imec-idlab team,
Firstly I would like to thank you for the valuable contribution 
to researchers working with IEEE 802.11ah.

I am working with some evaluations of dynamic RAW configurations. And I found a 
issue with the maximum number of slots. At the _line 62_ of _RPS.cc_ on the method _RPS::RawAssignment::SetSlotNum_ this only enables
it to be on the maximum _63_ when _slot format_ is _0_ and _7_ when _slot format_ is _1_. 
This is the code in RPS.cc:
```
RPS::RawAssignment::SetSlotNum (uint16_t count)
{
   NS_ASSERT((!m_SlotFormat & (count < 64)) || (m_SlotFormat & (count < 8)));
   m_slotNum = count;

}

```
But reading the [paper https://doi.org/10.3390/s18020325](https://doi.org/10.3390/s18020325) it says that the maximum number of slots are 64 (if slot format == 0) and 8 (if slot format ==  1).

Is it wrong in the code?

Thanks in advance for any clarification.

**Comment by asljivo1** [comment]
Hi, 

It is not wrong in the code. 

If slot format = 0, slot duration count field is 8 bits long, and number of slots field is 14-8=6 bits long, hence 63 as the largest value that can be encoded in the field.
If the slot format = 1, slot duration count field is 11 bits long, and number of slots field is 14-11=3 bits long, hence 7 as the largest value that can be encoded in the field.

**Comment by pedroliborio** [comment]
> Hi,
> 
> It is not wrong in the code.
> 
> If slot format = 0, slot duration count field is 8 bits long, and number of slots field is 14-8=6 bits long, hence 63 as the largest value that can be encoded in the field.
> If the slot format = 1, slot duration count field is 11 bits long, and number of slots field is 14-11=3 bits long, hence 7 as the largest value that can be encoded in the field.

Hi @asljivo1 , 
Thank you for you answer. 

Besides the representation go only up to 63, if we consider the value 0 as 1 slot per RAW and value 63 as 64 slots per RAW (the range goes from 0 to 63, so _64 different values_ can be encoded).

In this way we could represent up to 64 or 8 slots per RAW depending on the slot format. 

I made some tests with slot num value 0 (which could represent 1 slot per RAW) and the simulation crash. So I conclude the simulator only accepts values from 1 to 63 or 1 to 7 (value 0 isn't used).

Is am I wrong? I am making this question because I am evaluating some RAW configurations on network physical limits and evaluating different RAW configurations. 
The actual simulator code can only represent up to 63 (ranging from 1 to 63) or 7 (ranging from 1 to 7) slots?

Note this question is defferent of the early.

Thank you so much for you help.
Best Regards,

Pedro.

**Comment by asljivo1** [comment]
Hi,

You are not wrong. 1-63 and 1-7 it is indeed. 0 slots and 0 groups correspond to not configuring a RAW at all. However, it could be implemented in a way you suggested (value 0 to corrspond to 1 slot etc) but we did not do it.
