### ISSUE TITLE
Max contention window value possible mistake

### ISSUE THREAD

**Issue by YuliyanGeorgiev** [imec-idlab/IEEE-802.11ah-ns-3#18]
Hi all,

Recently I started working with the NS-3 extension of HaLow, which I found to be very nice. However, I noticed a possible mistake. I was trying to create a selfish node behavior when I found out the following:
![image](https://user-images.githubusercontent.com/19795353/120284931-70b22100-c2c5-11eb-8bd2-033200c416b5.png)
in the file sta-wifi-mac.cc. As you can see SetMaxCW uses the variable cwmin in the equation. Shouldn't that be cwmax instead? I see that cwmax is not used at all. In that case the CWmax is set to 16.

**Comment by ssi15004** [comment]
Good morning Yuliyan,
Thank you very much for pointing out this, we’ll look into this!

Kind regards,
Serena

On 1 Jun 2021, at 09:40, Yuliyan Georgiev ***@***.******@***.***>> wrote:


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Hi all,

Recently I started working with the NS-3 extension of HaLow, which I found to be very nice. However, I noticed a possible mistake. I was trying to create a selfish node behavior when I found out the following:
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F19795353%2F120284931-70b22100-c2c5-11eb-8bd2-033200c416b5.png&data=04%7C01%7Cserena.santi%40uantwerpen.be%7C35dba848aaee452700e608d924d08940%7C792e08fb2d544a8eaf72202548136ef6%7C0%7C0%7C637581301256484322%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ffdw3w8zizg1lh6RRRV37Ode0BFODispJ%2F%2Fs2e42DhM%3D&reserved=0>
in the file sta-wifi-mac.cc<http://sta-wifi-mac.cc>. As you can see SetMaxCW uses the variable cwmin in the equation. Shouldn't that be cwmax instead? I see that cwmax is not used at all.

**Comment by YuliyanGeorgiev** [comment]
Thank you for the reply,

I just want to add that I think that the values from the screenshot I took are not really used. The parameters are actually taken from the wifi-mac.cc I believe, but if you could give me some explanation I would appreciate it.
