### ISSUE TITLE
Question about RAW allocation

### ISSUE THREAD

**Issue by YuliyanGeorgiev** [imec-idlab/IEEE-802.11ah-ns-3#19]
Hello,

I have a question about the RAW allocation. Is it possible to allocate exact stations in a RAW group instead of giving a range only. For example if I would like to have stations 11 and 25 in the same RAW group and no other station, how can I do that?

Kind regards
Yuliyan Georgiev

**Comment by asljivo1** [comment]
Hi,

It is not possible to allocate exact stations in a RAW group that way, you have to specify range. What you can do is assign sequential AIDs to the two stations you wish to group together. To do this see how AIDs are assigned currently in main() and setstaid() in scratch/test/s1g-test-tim-raw.cc

**Comment by YuliyanGeorgiev** [comment]
Hi,

Thank you. I will try that.
