### ISSUE TITLE
Assert failed in StaWifiMac::S1gTIMReceived() 

### ISSUE THREAD

**Issue by hanjh85** [imec-idlab/IEEE-802.11ah-ns-3#3]
Hello,

I have read your papers related with 802.11ah, and currently I am trying out this 802.11ah simulator implemented on NS-3 for my research.

I followed your instruction on README.md to run the simulator, but everytime I run it, it terminates due to "NS_ASSERT(m_pageSlice.GetPageindex() == m_TIM.GetPageIndex());" at ./src/wifi/model/sta-wifi-mac.cc.

Below is the messages I get when the simulator terminates 

assert failed. cond="m_pageSlice.GetPageindex() == m_TIM.GetPageIndex()", file=../src/wifi/model/sta-wifi-mac.cc, line=407
terminate called without an active exception
Command ['/home/han/tarballs/ns-allinone-3.23/IEEE-802.11ah-ns-3/build/scratch/test/test', '--seed=1', '--simulationTime=60', '--payloadSize=256'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

Thank you.

**Comment by letiangit** [comment]
May i ask which operating system you are using? You can also try the following command for 'Configure waf':  
CXXFLAGS="-std=c++0x" ./waf configure --disable-examples --disable-tests
Make suer you use the code from 'master' branch, and the latest version.

**Comment by hanjh85** [comment]
I used the code from 'master' branch and ran it under Ubuntu 16.04.5. I tried your suggestion but I got the same error.

Which operating system should I use to run the simulator? In addition to that, is there other environmental factors that affect running the simulator? If so, can you suggest the environmental setup?

**Comment by letiangit** [comment]
We tested on Mac and  Ubuntu 16.04.4 and there was no errors.
Can you list all the command you used for running the code,  and the commit of the code?
Btw, have you made any changes on the code?

**Comment by hanjh85** [comment]
I tested on Fedora 26 and the simulator works fine.

For your information, below is all of the commands I put after I reinstalled Ubuntu 16.04.5, and still it shows the same error message. I do not made any changes on the code. 

Most of the commands are instructed from https://www.nsnam.org/wiki/Installation. There is one thing I failed to follow that NS3 instruction. I failed to install the package "libc6-dev-i386", but it might not be the reason of the error.


    1  apt-get install gcc g++ python
    2  sudo apt-get install gcc g++ python
    3  sudo apt-get install python-dev
    4  sudo apt-get install mercurial python-setuptools git qt5-default
    5  apt-get install python-pygraphviz python-kiwi python-pygoocanvas libgoocanvas-dev ipython
    6  sudo apt-get install python-pygraphviz python-kiwi python-pygoocanvas libgoocanvas-dev ipython
    7  sudo apt-get install openmpi-bin openmpi-common openmpi-doc libopenmpi-dev
    8  sudo apt-get install autoconf cvs bzr unrar
    9  sudo apt-get install gdb valgrind unrustify
   10  sudo apt-get install gdb valgrind 
   11  sudo apt-get install uncrustify
   12  sudo apt-get install doxygen graphviz imagemagick
   13  sudo apt-get install gsl-bin libgsl2 libgsl-dev
   14  sudo apt-get install flex bison libfl-dev
   15  sudo apt-get install tcpdump
   16  sudo apt-get install sqlite sqlite3 libsqlite3-dev
   17  sudo apt-get install libxml2 libxml2-dev
   18  sudo apt-get install cmake libc6-dev libc6-dev-i386 libclang-dev llvm-dev automake
   19  sudo apt-get install cmake libc6-dev libclang-dev llvm-dev automake
   20  sudo apt-cache search lib6-dev*
   21* sudo apt-cache search lib6-
   22  sudo apt-cache search lib6-dev-*
   23  sudo apt-cache search "lib6-dev*"
   24  sudo apt-cache search "lib6-*"
   25  pip install cxxfilt
   26  sudo pip install cxxfilt
   27  sudo apt-get install gcc g++ python python-dev
   28  apt-get install pip
   29  sudo apt-get install pip
   30  pip
   31  sudo apt-get install python-pip
   32  pip install cxxfilt
   33  sudo apt-get install libgtk2.0-0 libgtk2.0-dev
   34  sudo apt-get install vtun lxc
   35  sudo apt-get install libboost-signals-dev libboost-filesystem-dev
   36  git clone https://github.com/imec-idlab/IEEE-802.11ah-ns-3
   37  cd IEEE-802.11ah-ns-3/
   38  CXXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests
   39  ./waf
   40  ./waf --run test
   41  sudo apt-get install libclang-6.0-dev llvm-6.0-dev
   42  ./waf clean
   43  CXXFLAGS="-std=c++11" ./waf configure --disable-examples --disable-tests
   44  ./waf
   45  ls
   46  ./waf --run test
   47  history
   48  history >> cmd_history.txt

**Comment by letiangit** [comment]
Can you print the values of  "m_pageSlice.GetPageindex()" and "m_TIM.GetPageIndex()", before the code "NS_ASSERT(m_pageSlice.GetPageindex() == m_TIM.GetPageIndex())". 
Maybe run several times, to see whether  the values  change or  are fixed.

**Comment by hanjh85** [comment]
m_pageSlice.GetPageindex() : 0
m_TIM.GetPageIndex() : 2

Every time I run it, it shows the same value of them.

**Comment by letiangit** [comment]
It's really strange, they are both 0 for us. As we cannot reproduce the error you have for the moment. there are two things you can do:
1, Try to debug the TIM element, look at the function like 'TIM::SetPageIndex ()', 'TIM::SetPageIndex ()',
'TIM::SetBitmapControl ()', and 'TIM::DeserializeInformationField ()', 'TIM::SerializeInformationField'.
Check whether  the information write into the TIM element and read from the TIM element are the same or not.

2, Try the following command:
sudo apt-get update
sudo apt-get -y install gcc g++ python
sudo apt-get -y install gcc g++ python python-dev
sudo apt-get -y install qt4-dev-tools libqt4-dev
sudo apt-get -y install mercurial
sudo apt-get -y install bzr
sudo apt-get -y install cmake libc6-dev libc6-dev-i386 g++-multilib
sudo apt-get -y install gdb valgrind
sudo apt-get -y install gsl-bin libgsl2 libgsl2:i386
sudo apt-get -y install flex bison libfl-dev
sudo apt-get -y install tcpdump
sudo apt-get -y install sqlite sqlite3 libsqlite3-dev
sudo apt-get -y install libxml2 libxml2-dev
sudo apt-get -y install libgtk2.0-0 libgtk2.0-dev
sudo apt-get -y install vtun lxc
sudo apt -y install git
git clone https://github.com/imec-idlab/IEEE-802.11ah-ns-3.git
cd IEEE-802.11ah-ns-3
CXXFLAGS="-std=c++11" ./waf configure --build-profile=debug --disable-examples --disable-tests
./waf -j4
./waf --run test
Hope it works. 

At meantime, we will also try to reproduce the error you have and solve the problem.
