### ISSUE TITLE
RAW configuration

### ISSUE THREAD

**Issue by Mohmoulay** [imec-idlab/IEEE-802.11ah-ns-3#4]
Hi! Thanks for your amazing project. I've got a small issue with the RAW configuration, well I've done the same configuration for the first two rps to accommodate 100 STA, but after the third RPS I get 
assert failed. cond="x", file=../src/wifi/model/ap-wifi-mac.cc, line=621
terminate called without an active exception
It doesn't make sense since I just try to repeat this for more STA. Am I missing something?

**Comment by Mohmoulay** [comment]
I am checking the ./RawGenerate.sh I think it's a miss configuration from my end?

**Comment by letiangit** [comment]
I find some misconfigurations. For example,   0	1	0	2	50	1	1	49,
1, The NRawSlotCount is only 2, which is too small, you may need to make it bigger. However, this should not cause the error you have.
2, In the simulator, it assumes the AID of stations is same as mac address, as you can find in https://github.com/imec-idlab/IEEE-802.11ah-ns-3/blob/master/src/wifi/model/ap-wifi-mac.cc, line 771. For 100 stations, their page index should be 0 instead of 1. In your configuration, no stations are assigned to the RAW groups, this might be the reason.

**Comment by Mohmoulay** [comment]
Thanks for your help. I've tried the mentioned above and with no avail. The reason behind the small Tslot is due to the small payloadSize. I will try and let you know how it went!. Thanks!

**Comment by Mohmoulay** [comment]
Still I get this error in the ap-wifi-mac.cc 
------------------------------------------------------------------------------------------------
At time 9.5802s client=192.168.0.46 sent 20 bytes to 192.168.1.45 port 9
At time 9.58513s server=192.168.1.45 received 20 bytes from 192.168.0.46 port 49153
At time 9.58513s server=192.168.1.45 sent 20 bytes to 192.168.0.46 port 49153
At time 9.5922s client=192.168.0.202 sent 20 bytes to 192.168.1.45 port 9
At time 9.59713s server=192.168.1.45 received 20 bytes from 192.168.0.202 port 49153
assert failed. cond="x", file=../src/wifi/model/ap-wifi-mac.cc, line=621
terminate called without an active exception
-------------------------------------------------------------------------
I tried also with the examples provided in the optimalrawgrup folder, but if you go above a certain number of STA things go wrong, also I've generating the rawconfig file using the bash script and I still get the error even tho If I comment   NS_ASSERT (x); it works!.

**Comment by asljivo1** [comment]
You have the error beacue RAW configuration is not in line with TIM configuration. You configured 3 RAW groups, each one being in different beacon interval and you didn't change your TIM configuration which by default assumes every beacon is DTIM (in your case every 3rd beacon should be DTIM). The command ./waf --run  "test --seed=1 --simulationTime=60 --payloadSize=20 --TrafficType="udpecho" --pagePeriod=3 --pageSliceLength=1 --pageSliceCount=3 " is the TIM configuration you are looking for. However, in AID hierarchy stations are distributed to pages, blocks and sub-blocks. You assign blocks to TIM groups, and one block has 64 stations (except the last one, the last one can have less or more, basically all remaining stations that are not assigned to previous TIMs are assigned to last TIM). Therefore, your RAW configuration should be:
3
1
0   1   0   2   50   1   1   63
1
0   1   0   2   50   1   64   127
1
0   1   0   2   50   1   128   149

**Comment by Mohmoulay** [comment]
Thanks! for the explanation you made everything clear and obvious! highly appreciate it. Let's close this non issue
