### ISSUE TITLE
Question about ns3 802.11ah RAWconfig Interface

### ISSUE THREAD

**Issue by soczysty7** [imec-idlab/IEEE-802.11ah-ns-3#7]
**Thanks** for your contribution to development of ns3 802.11ah module.
I am now doing research using this solution and it works really well.

I performed multiple experiments configuring the simulation scenario bundles provided on project's github. However I also wanted to work with grouping mechanisms. As specified in "Implementation and Validation of an IEEE 802.11ah Module for ns-3" and "Extension of the IEEE 802.11ah ns-3 Simulation Module" this should be achieved by fine-tuning the interaction between RAWConfigurationInterface & Ap/StaWifiMac.

I wanted to first start with TAROA which you proposed in "Real-Time Station Grouping under Dynamic Traffic for IEEE 802.11ah" and progress to "IEEE 802.11ah Restricted Access Window Surrogate Model for Real-Time Station Grouping" eventually my own schemas. I believe main functionality described in TAROA article is in s1g-raw-control.cc : for example EstimateTransmissionInterval seems to implement 'Algorithm 1: Estimate transmission interval of station s ∈ S' Also S1gRawCtr::UdpateSensorStaInfo looks important.

Anyway, could you please give me some hints on _how to switch from static-RAWconfig to dynamic use of S1gRawCtr ?_ The code base is large for me and it feels difficult to navigate through it.

Best Regards,

Michał Piech

**Comment by asljivo1** [comment]
Hi Michał ,

First of all, sorry for the late response. 

The commented lines 1021-1028 in ap-wifi-mac.cc call the dynamic updating of RAW on the m_s1gRawCtr object. As you wrote, s1g-raw-control.cc implements all methods used for RAW optimization, but optimization is called by the AP (from ApWifiMac::SendOneBeacon). TAROA uses certain measurements that AP collected such as whether a TX was successful in the last RAW, last success time etfc. Whatever data your algorithm uses, you need to collect it of course. In the available code that is done in UpdateSensorStaInfo. m_sta object of type "Sensor" stores the particular data for each sensor station. Later on, this data is used to group similar stations together. I did not implement the algorithm myself so I wouldn't go into details, but your starting point for implementing your RAW optimization algorithm would be ApWifiMac::SendOneBeacon from where the S1gRawCtr::UpdateRAWGroupping is called which first organizes the previously measured data used in the algorithm and then calculates everything needed to determine the the optimal RAWs, and finally assigns the corresponding stations to RAWs. Thus, "the most important" function to see is S1gRawCtr::UpdateRAWGroupping.

Kind regards,
Amina

**Comment by soczysty7** [comment]
Thanks a lot for your reply Amina !

In order to launch TAROA :

... in ap-wifi-mac.cc I  

- 	uncommented 1021-1028
- 	commented 	977 - 990
- 	to be able to compile switched all -> to dot operator in m_rps.GetRawAssigmentObj() :
	lines (not sure if should have done that)

I see **UpdateRAWGroupping** has been called because "stationfiles" were created for 17 allowed stations:
	m_numSendSensorAllowed = 17 from the log

Also enabled the logs 
```
	 LogComponentEnable("s1g-wifi-network-tim-raw", LOG_DEBUG);
	 LogComponentEnable ("S1gRawCtr", LOG_DEBUG);
	 LogComponentEnable ("ApWifiMac", LOG_DEBUG);
```
The .nss output file ends with ;stanodeassoc info for these allowed nodes.

The simulation starts however  there occurs Segmentation fault in ns3::RPS::GetRawAssignment() function. Below I paste the call graph 

![image](https://user-images.githubusercontent.com/25151031/58374647-f6b26900-7f41-11e9-865b-1ae5aeae6364.png)

And the callstack from gdb debugger : 

0.  0x00007ffff1b9abe2 in **ns3::RPS::GetRawAssignment()** const ()

1.  0x00007ffff1b9ac23 in **ns3::RPS::GetRawAssigmentObj**(unsigned int) const ()
   
2.  0x000000000047da40 in **onChannelTransmission**(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>) ()

3.  0x000000000049dd20 in ns3::FunctorCallbackImpl<void (*)(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>), void, ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty>::operator()(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>) ()

4.  0x00007ffff1a25444 in ns3::Callback<void, ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty>::operator()(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>) const ()
   
5.  0x00007ffff1a244cb in ns3::TracedCallback<ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty, ns3::empty>::operator()(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::Packet>) const ()
   
6.  0x00007ffff1a22f17 in ns3::YansWifiChannel::Send(ns3::Ptr<ns3::YansWifiPhy>, ns3::Ptr<ns3::Packet const>, double, ns3::WifiTxVector, ns3::WifiPreamble, unsigned char, ns3::Time) const ()
   
7.  0x00007ffff1a123a7 in ns3::YansWifiPhy::SendPacket(ns3::Ptr<ns3::Packet const>, ns3::WifiTxVector, ns3::WifiPreamble, unsigned char) ()
   
8.  0x00007ffff1a3c25c in **ns3::MacLow::ForwardDown**(ns3::Ptr<ns3::Packet const>, ns3::WifiMacHeader const*, ns3::WifiTxVector, ns3::WifiPreamble) ()
   
9.  0x00007ffff1a41eec in **ns3::MacLow::SendDataPacket() ()**
   
10. 0x00007ffff1a320d8 in ns3::MacLow::StartTransmission(ns3::Ptr<ns3::Packet const>, ns3::WifiMacHeader const*, ns3::MacLowTransmissionParameters, ns3::MacLowTransmissionListener*) ()
   
11. 0x00007ffff1a71317 in ns3::DcaTxop::NotifyAccessGranted() ()
   
12. 0x00007ffff1a76a70 in ns3::DcaTxop::Dcf::DoNotifyAccessGranted() ()
   
13. 0x00007ffff1a883ce in **ns3::DcfState::NotifyAccessGranted() ()**
   
14. 0x00007ffff1a8cdf1 in **ns3::DcfManager::DoGrantAccess() ()**
   
15. 0x00007ffff1a8c4b9 in **ns3::DcfManager::RequestAccess(ns3::DcfState*) ()**
   
16. 0x00007ffff1a6d2ae in **ns3::DcaTxop::StartAccessIfNeeded() ()**
   
17. 0x00007ffff1a6c734 in **ns3::DcaTxop::Queue**(ns3::Ptr<ns3::Packet const>, ns3::WifiMacHeader const&) ()
   
18. 0x00007ffff1ad4942 in **ns3::ApWifiMac::SendOneBeacon() ()**
   
19. 0x00007ffff1ade461 in ns3::MakeEvent<void (ns3::ApWifiMac::*)(), ns3::ApWifiMac*>(void (ns3::ApWifiMac::*)(), ns3::ApWifiMac*)::EventMemberImpl0::Notify()
    ()
   
20. 0x00007fffef921875 in **ns3::EventImpl::Invoke() ()**
   
21. 0x00007fffef92698d in **ns3::DefaultSimulatorImpl::ProcessOneEvent() ()**
   
22. 0x00007fffef926da1 in **ns3::DefaultSimulatorImpl::Run() ()**
   
23. 0x00007fffef9226ed in **ns3::Simulator::Run() ()**

24. 0x0000000000489683 **in main ()**

Probably I have some misconfiguration related to RPS class. Maybe some invalid parameters are overwritten by configuration.h or the GetRawAssigmentObj() is called 
improperly ?
Could you please suggest some changes if this is a known issue ?
I attach obtained simulation files : 

[sig_segv_taroa_issue.zip.zip](https://github.com/imec-idlab/IEEE-802.11ah-ns-3/files/3219758/sig_segv_taroa_issue.zip.zip)

Best regards & thanks for help,
Michał

**Comment by letiangit** [comment]
Hi Michał,

There are several things you can look at.

First, there is no throughput at all, specifically,  "m_receivedAid = 0" in the log file. I suppose there is some thing wrong, can you check how is stations group, and why no output.

Second, find out the error of "ns3::RPS::GetRawAssignment() " is from the station side or AP side.  If it's from the AP side, again check how is station grouped, i.e., the RAW configuration in  m_s1gRawCtr class,  function S1gRawCtr::configureRAW ( ).

**Comment by Fly-dusk** [comment]
I have also encountered the same problem as Michał. If you has already solved it, could you give me a some hints about the error
"terminated with signal SIGSEGV" after  I "uncommented 1021-1028, commented 977 - 990 and the dot operator ".Thanks very much.

![3c1389cd0fe638e543f9aceb289d640](https://github.com/imec-idlab/IEEE-802.11ah-ns-3/assets/155744728/32166568-8bbc-4e80-a3f9-c52943703ec6)
